// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV32wPmN93tgk-PAzydZecNi2lwd3MORw',
    appId: '1:31945787831:web:c12b8d0f93f68c3ae8c032',
    messagingSenderId: '31945787831',
    projectId: 'travery-9ef7c',
    authDomain: 'travery-9ef7c.firebaseapp.com',
    storageBucket: 'travery-9ef7c.firebasestorage.app',
    measurementId: 'G-QYM4M93ZF2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4U3qgyaz3fdfzgPjiDs78n2XgEBeP9n8',
    appId: '1:31945787831:android:6a834b1a0ea7ca9ee8c032',
    messagingSenderId: '31945787831',
    projectId: 'travery-9ef7c',
    storageBucket: 'travery-9ef7c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUwGsdSnPQ2EF40-nQ-8b32FUL6D5Tn00',
    appId: '1:31945787831:ios:7be2af46852f6b85e8c032',
    messagingSenderId: '31945787831',
    projectId: 'travery-9ef7c',
    storageBucket: 'travery-9ef7c.firebasestorage.app',
    iosBundleId: 'com.example.traveryFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUwGsdSnPQ2EF40-nQ-8b32FUL6D5Tn00',
    appId: '1:31945787831:ios:7be2af46852f6b85e8c032',
    messagingSenderId: '31945787831',
    projectId: 'travery-9ef7c',
    storageBucket: 'travery-9ef7c.firebasestorage.app',
    iosBundleId: 'com.example.traveryFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCV32wPmN93tgk-PAzydZecNi2lwd3MORw',
    appId: '1:31945787831:web:3b34c518384b2cc4e8c032',
    messagingSenderId: '31945787831',
    projectId: 'travery-9ef7c',
    authDomain: 'travery-9ef7c.firebaseapp.com',
    storageBucket: 'travery-9ef7c.firebasestorage.app',
    measurementId: 'G-ERS1984Y5D',
  );
}
